/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.btn

fun main() {
    val retryRiver = RetryRiver(
            retryTopic = TOPIC_RETRY_OPPGAVE_OPPRETTELSE,
            producerTopic = TOPIC_MELDING_MED_OPPGAVE,
            deadLetterTopic = TOPIC_MULTIPLE_FAILING_SERVICE_CALLS
    )

    Runtime.getRuntime().addShutdownHook(Thread {
        retryRiver.stop()
    })

    retryRiver.start()
}
